[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.32.0", features = ["full"] }
color-eyre = "0.6.2"

[dev-dependencies]
clap = { version = "4.5.2", features = ["derive"] }